spring:
  application:
    name: for-mountain
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  data:
    redis:
      host: localhost
      port: 6379

  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 3600

server:
  forward-headers-strategy: framework
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
